apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-now-api-deployment
  labels:
    app: bank-now-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-now-api
  template:
    metadata:
      labels:
        app: bank-now-api
    spec:
      containers:
      - name: bank-now-api
        image: loosec9n/bank.now:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bank-now-api-service
spec:
  selector:
    # app.kubernetes.io/name: bank-now-api
    app: bank-now-api
  type: NodePort
# type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31000