apiVersion: v1
kind: Service
metadata:
  name: bank-now-api-service
spec:
  selector:
    app.kubernetes.io/name: bank-now-api
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036
  # type: LoadBalancer